global: 
  sdncImgtag: 13.4.0.1010739
  namespace:
    name: demo
    create: false
launchpad:
  launchpad:
    appSelector: aeo
    image:
      tag: 13.4.0.1010742
    upgradeFrom: 13.4.0.1010742
  aeo:
    image:
      controller:
        tag: 13.4.0.1010742
        pullPolicy: IfNotPresent
      serviceWorker:
        tag: 13.4.0.1010742
        pullPolicy: IfNotPresent
      resourceWorker:
        tag: 13.4.0.1010742
        pullPolicy: IfNotPresent
      tmfServer:
        tag: 13.4.0.1010742
        pullPolicy: IfNotPresent
      scriptExec:
        pullPolicy: IfNotPresent

