global: 
  sdncImgtag: 13.3.1.1010254
  namespace:
    name: zhone
    create: true
launchpad:
  launchpad:
    appSelector: aeo
    image:
      repository: rt.cloud.dzsi.local/docker/rw.aeo
      tag: 13.3.1.1010260
    upgradeFrom: null
  aeo:
    image:
      controller:
        tag: 13.3.1.1010260
        pullPolicy: IfNotPresent
      serviceWorker:
        tag: 13.3.1.1010260
        pullPolicy: IfNotPresent
      resourceWorker:
        tag: 13.3.1.1010260
        pullPolicy: IfNotPresent
      tmfServer:
        tag: 13.3.1.1010260
        pullPolicy: IfNotPresent
      scriptExec:
        pullPolicy: IfNotPresent

