{{- if .Values.serviceAccountCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{  .Values.global.namespace.name }}
  labels:
    app: {{ template "strimzi.name" . }}
    chart: {{ template "strimzi.chart" . }}
    component: service-account
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
