# Copyright 2024 DZS Inc
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhone-sdnc-gnpy
  namespace: {{ include "sdnc.namespace" . }}
  labels:
    {{- include "gnpy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gnpy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gnpy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.sdncImgtag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
