{{- if .Values.global.nodeportServiceEnable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.nodeportService.name }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    app: {{ .Values.global.nodeportService.appLabel }}
spec:
  type: NodePort
  selector:
    run: haproxy-ingress
  ports:
    - name: redis-8014
      port: {{ .Values.global.nodeportService.ports.redis }}
      targetPort: 8014
      protocol: TCP
      nodePort: {{ .Values.global.nodeportService.nodePorts.redis }}
    - name: mongo-8006
      port: {{ .Values.global.nodeportService.ports.mongo }}
      targetPort: 8006
      protocol: TCP
      nodePort: {{ .Values.global.nodeportService.nodePorts.mongo }}
{{- end }}
