{{- if .Values.global.nodeportServiceEnable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.nodeportService.name | default "nodeport-rm" }}
  namespace: {{ .Values.global.namespace.name | default "nfvso" }}
  labels:
    app: {{ .Values.global.nodeportService.appLabel | default "xtreme" }}
spec:
  type: NodePort
  selector:
    run: haproxy-ingress
  ports:
    - name: redis-8014
      port: {{ default 5053 .Values.global.nodeportService.ports.redis }}
      targetPort: 8014
      protocol: TCP
      nodePort: {{ .Values.global.nodeportService.nodePorts.redis | default 31015 }}
    - name: mongo-8006
      port: {{ default 5063 .Values.global.nodeportService.ports.mongo }}
      targetPort: 8006
      protocol: TCP
      nodePort: {{ .Values.global.nodeportService.nodePorts.mongo | default 32015 }}
{{- end }}
